=== Madolkke/cli-parser/evals/test_sets/fortinet.get_system_status/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "string"
    },
    "firmware_signature": {
      "type": "string"
    },
    "virus_db": {
      "type": "string"
    },
    "extended_db": {
      "type": "string"
    },
    "av_ai_ml_model": {
      "type": "string"
    },
    "ips_db": {
      "type": "string"
    },
    "ips_etdb": {
      "type": "string"
    },
    "app_db": {
      "type": "string"
    },
    "industrial_db": {
      "type": "string"
    },
    "ips_malicious_url_database": {
      "type": "string"
    },
    "serial_number": {
      "type": "string"
    },
    "bios_version": {
      "type": "string"
    },
    "system_part_number": {
      "type": "string"
    },
    "log_hard_disk": {
      "type": "string"
    },
    "hostname": {
      "type": "string"
    },
    "private_encryption": {
      "type": "string"
    },
    "operation_mode": {
      "type": "string"
    },
    "current_virtual_domain": {
      "type": "string"
    },
    "max_number_of_virtual_domains": {
      "type": "string"
    },
    "virtual_domains_status": {
      "type": "string"
    },
    "virtual_domain_configuration": {
      "type": "string"
    },
    "fips_cc_mode": {
      "type": "string"
    },
    "current_ha_mode": {
      "type": "string"
    },
    "branch_point": {
      "type": "string"
    },
    "release_version_information": {
      "type": "string"
    },
    "system_time": {
      "type": "string"
    },
    "last_reboot_reason": {
      "type": "string"
    },
    "security_level": {
      "type": "string"
    },
    "cluster_uptime": {
      "type": "string"
    },
    "cluster_state_change_time": {
      "type": "string"
    },
    "extreme_db": {
      "type": "string"
    },
    "fortios_x86_64": {
      "type": "string"
    }
  },
  "required": [
    "version",
    "firmware_signature",
    "virus_db",
    "extended_db",
    "av_ai_ml_model",
    "ips_db",
    "ips_etdb",
    "app_db",
    "industrial_db",
    "ips_malicious_url_database",
    "serial_number",
    "bios_version",
    "system_part_number",
    "log_hard_disk",
    "hostname",
    "private_encryption",
    "operation_mode",
    "current_virtual_domain",
    "max_number_of_virtual_domains",
    "virtual_domains_status",
    "virtual_domain_configuration",
    "fips_cc_mode",
    "current_ha_mode",
    "branch_point",
    "release_version_information",
    "system_time",
    "last_reboot_reason"
  ]
}

=== Madolkke/cli-parser/evals/test_sets/fortinet.get_system_status/expected.json
[
  {
    "last_reboot_reason": "warm reboot",
    "system_time": "Sun Nov 27 00:26:34 2022",
    "release_version_information": "GA",
    "branch_point": "0367",
    "current_ha_mode": "standalone",
    "fips_cc_mode": "disable",
    "virtual_domain_configuration": "disable",
    "virtual_domains_status": "1 in NAT mode, 0 in TP mode",
    "max_number_of_virtual_domains": "10",
    "current_virtual_domain": "root",
    "operation_mode": "NAT",
    "private_encryption": "Disable",
    "hostname": "fw1",
    "log_hard_disk": "Not available",
    "system_part_number": "P24286-03",
    "bios_version": "05000009",
    "serial_number": "FGT60xxxxxxxxxxx",
    "ips_malicious_url_database": "4.00542(2022-11-26 11:33)",
    "industrial_db": "6.00741(2015-12-01 02:30)",
    "app_db": "22.00444(2022-11-22 02:49)",
    "ips_etdb": "0.00000(2001-01-01 00:00)",
    "ips_db": "22.00446(2022-11-24 01:49)",
    "av_ai_ml_model": "2.05720(2022-05-23 11:45)",
    "extended_db": "90.02571(2022-05-23 20:26)",
    "virus_db": "90.02571(2022-05-23 20:26)",
    "firmware_signature": "certified",
    "version": "FortiGate-60F v7.0.7,build0367,221005 (GA.F)"
  },
  {
    "last_reboot_reason": "warm reboot",
    "system_time": "Fri Oct 11 14:01:48 2024",
    "release_version_information": "GA",
    "branch_point": "0632",
    "cluster_state_change_time": "2024-10-02 20:32:30",
    "cluster_uptime": "31 days, 21 hours, 46 minutes, 28 seconds",
    "current_ha_mode": "a-p, primary",
    "fips_cc_mode": "disable",
    "virtual_domain_configuration": "disable",
    "virtual_domains_status": "1 in NAT mode, 0 in TP mode",
    "max_number_of_virtual_domains": "10",
    "current_virtual_domain": "root",
    "operation_mode": "NAT",
    "private_encryption": "Disable",
    "hostname": "FGT-fw-a",
    "log_hard_disk": "Not available",
    "system_part_number": "P24680-03",
    "bios_version": "05000003",
    "serial_number": "FGT40XXXXXXXXXXX",
    "ips_malicious_url_database": "3.00309(2022-04-03 15:27)",
    "industrial_db": "6.00741(2015-12-01 02:30)",
    "app_db": "6.00741(2015-12-01 02:30)",
    "ips_etdb": "0.00000(2001-01-01 00:00)",
    "ips_db": "6.00741(2015-12-01 02:30)",
    "av_ai_ml_model": "0.00000(2001-01-01 00:00)",
    "extended_db": "1.00000(2018-04-09 18:07)",
    "virus_db": "1.00000(2018-04-09 18:07)",
    "firmware_signature": "certified",
    "security_level": "1",
    "version": "FortiGate-40F v7.0.15,build0632,240401 (GA.M)"
  },
  {
    "last_reboot_reason": "warm reboot",
    "system_time": "Fri Oct 11 14:24:22 2024",
    "fortios_x86_64": "Yes",
    "release_version_information": "GA",
    "branch_point": "0566",
    "cluster_state_change_time": "2024-07-29 03:45:36",
    "cluster_uptime": "85 days, 12 hours, 38 minutes, 8 seconds",
    "current_ha_mode": "a-p, primary",
    "fips_cc_mode": "disable",
    "virtual_domain_configuration": "disable",
    "virtual_domains_status": "1 in NAT mode, 0 in TP mode",
    "max_number_of_virtual_domains": "10",
    "current_virtual_domain": "root",
    "operation_mode": "NAT",
    "private_encryption": "Disable",
    "hostname": "FGT",
    "log_hard_disk": "Available",
    "system_part_number": "P25035-04",
    "bios_version": "05000011",
    "serial_number": "FG181XXXXXXXXXXX",
    "ips_malicious_url_database": "1.00001(2015-01-01 01:01)",
    "industrial_db": "6.00741(2015-12-01 02:30)",
    "app_db": "6.00741(2015-12-01 02:30)",
    "ips_etdb": "6.00741(2015-12-01 02:30)",
    "ips_db": "6.00741(2015-12-01 02:30)",
    "av_ai_ml_model": "0.00000(2001-01-01 00:00)",
    "extreme_db": "1.00000(2018-04-09 18:07)",
    "extended_db": "90.09933(2023-01-24 02:26)",
    "virus_db": "90.09933(2023-01-24 02:26)",
    "firmware_signature": "certified",
    "security_level": "1",
    "version": "FortiGate-1801F v7.0.13,build0566,231024 (GA.M)"
  }
]
