=== Madolkke/cli-parser/evals/test_sets/cisco_ios.show_ip_ospf_database_router/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "router_id": {
      "type": "string"
    },
    "process_id": {
      "type": "string"
    },
    "area_id": {
      "type": "string"
    },
    "lsas": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "ls_age": {
            "type": "string"
          },
          "options": {
            "type": "string"
          },
          "ls_type": {
            "type": "string"
          },
          "link_state_id": {
            "type": "string"
          },
          "advertising_router": {
            "type": "string"
          },
          "ls_seq_number": {
            "type": "string"
          },
          "checksum": {
            "type": "string"
          },
          "length": {
            "type": "string"
          },
          "number_of_links": {
            "type": "string"
          },
          "links": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "link_type": {
                  "type": "string"
                },
                "link_id_label": {
                  "type": "string"
                },
                "link_id": {
                  "type": "string"
                },
                "link_data_label": {
                  "type": "string"
                },
                "link_data": {
                  "type": "string"
                },
                "mtid_metrics": {
                  "type": "string"
                },
                "tos0_metrics": {
                  "type": "string"
                }
              },
              "required": [
                "link_type",
                "link_id_label",
                "link_id",
                "link_data_label",
                "link_data",
                "mtid_metrics",
                "tos0_metrics"
              ]
            }
          }
        },
        "required": [
          "ls_age",
          "options",
          "ls_type",
          "link_state_id",
          "advertising_router",
          "ls_seq_number",
          "checksum",
          "length",
          "number_of_links",
          "links"
        ]
      }
    }
  },
  "required": [
    "router_id",
    "process_id",
    "area_id",
    "lsas"
  ]
}

=== Madolkke/cli-parser/evals/test_sets/cisco_ios.show_ip_ospf_database_router/expected.json
[
  {
    "router_id": "100.1.1.1",
    "process_id": "1",
    "area_id": "0",
    "lsas": [
      {
        "number_of_links": "4",
        "length": "72",
        "checksum": "0x8A21",
        "ls_seq_number": "80000206",
        "advertising_router": "100.1.1.1",
        "link_state_id": "100.1.1.1",
        "ls_type": "Router Links",
        "options": "(No TOS-capability, DC)",
        "ls_age": "14",
        "links": [
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Network Mask",
            "link_data": "255.255.255.255",
            "link_id_label": "Network/subnet number",
            "link_id": "100.1.1.1",
            "link_type": "a Stub Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.2.1",
            "link_id_label": "Designated Router address",
            "link_id": "192.168.2.1",
            "link_type": "a Transit Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.1.1",
            "link_id_label": "Neighboring Router ID",
            "link_id": "100.3.3.3",
            "link_type": "another Router (point-to-point)"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Network Mask",
            "link_data": "255.255.255.252",
            "link_id_label": "Network/subnet number",
            "link_id": "192.168.1.0",
            "link_type": "a Stub Network"
          }
        ]
      },
      {
        "number_of_links": "3",
        "length": "60",
        "checksum": "0xCA4F",
        "ls_seq_number": "80000202",
        "advertising_router": "100.2.2.2",
        "link_state_id": "100.2.2.2",
        "ls_type": "Router Links",
        "options": "(No TOS-capability, DC)",
        "ls_age": "1694",
        "links": [
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Network Mask",
            "link_data": "255.255.255.255",
            "link_id_label": "Network/subnet number",
            "link_id": "100.2.2.2",
            "link_type": "a Stub Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.3.1",
            "link_id_label": "Designated Router address",
            "link_id": "192.168.3.2",
            "link_type": "a Transit Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.2.2",
            "link_id_label": "Designated Router address",
            "link_id": "192.168.2.1",
            "link_type": "a Transit Network"
          }
        ]
      },
      {
        "number_of_links": "4",
        "length": "72",
        "checksum": "0x3969",
        "ls_seq_number": "800001FD",
        "advertising_router": "100.3.3.3",
        "link_state_id": "100.3.3.3",
        "ls_type": "Router Links",
        "options": "(No TOS-capability, DC)",
        "ls_age": "15",
        "links": [
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Network Mask",
            "link_data": "255.255.255.255",
            "link_id_label": "Network/subnet number",
            "link_id": "100.3.3.3",
            "link_type": "a Stub Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.4.1",
            "link_id_label": "Designated Router address",
            "link_id": "192.168.4.2",
            "link_type": "a Transit Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.1.2",
            "link_id_label": "Neighboring Router ID",
            "link_id": "100.1.1.1",
            "link_type": "another Router (point-to-point)"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Network Mask",
            "link_data": "255.255.255.252",
            "link_id_label": "Network/subnet number",
            "link_id": "192.168.1.0",
            "link_type": "a Stub Network"
          }
        ]
      },
      {
        "number_of_links": "3",
        "length": "60",
        "checksum": "0x5CB0",
        "ls_seq_number": "800001F7",
        "advertising_router": "100.4.4.4",
        "link_state_id": "100.4.4.4",
        "ls_type": "Router Links",
        "options": "(No TOS-capability, DC)",
        "ls_age": "1752",
        "links": [
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Network Mask",
            "link_data": "255.255.255.255",
            "link_id_label": "Network/subnet number",
            "link_id": "100.4.4.4",
            "link_type": "a Stub Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.4.2",
            "link_id_label": "Designated Router address",
            "link_id": "192.168.4.2",
            "link_type": "a Transit Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.3.2",
            "link_id_label": "Designated Router address",
            "link_id": "192.168.3.2",
            "link_type": "a Transit Network"
          }
        ]
      }
    ]
  },
  {
    "router_id": "100.1.1.1",
    "process_id": "1",
    "area_id": "0",
    "lsas": [
      {
        "number_of_links": "4",
        "length": "72",
        "checksum": "0x8A21",
        "ls_seq_number": "80000206",
        "advertising_router": "100.1.1.1",
        "link_state_id": "100.1.1.1",
        "ls_type": "Router Links",
        "options": "(No TOS-capability, DC)",
        "ls_age": "14",
        "links": [
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Network Mask",
            "link_data": "255.255.255.255",
            "link_id_label": "Network/subnet number",
            "link_id": "100.1.1.1",
            "link_type": "a Stub Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.2.1",
            "link_id_label": "Designated Router address",
            "link_id": "192.168.2.1",
            "link_type": "a Transit Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.1.1",
            "link_id_label": "Neighboring Router ID",
            "link_id": "100.3.3.3",
            "link_type": "another Router (point-to-point)"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Network Mask",
            "link_data": "255.255.255.252",
            "link_id_label": "Network/subnet number",
            "link_id": "192.168.1.0",
            "link_type": "a Stub Network"
          }
        ]
      },
      {
        "number_of_links": "3",
        "length": "60",
        "checksum": "0xCA4F",
        "ls_seq_number": "80000202",
        "advertising_router": "100.2.2.2",
        "link_state_id": "100.2.2.2",
        "ls_type": "Router Links",
        "options": "(No TOS-capability, DC)",
        "ls_age": "1694",
        "links": [
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Network Mask",
            "link_data": "255.255.255.255",
            "link_id_label": "Network/subnet number",
            "link_id": "100.2.2.2",
            "link_type": "a Stub Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.3.1",
            "link_id_label": "Designated Router address",
            "link_id": "192.168.3.2",
            "link_type": "a Transit Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.2.2",
            "link_id_label": "Designated Router address",
            "link_id": "192.168.2.1",
            "link_type": "a Transit Network"
          }
        ]
      },
      {
        "number_of_links": "4",
        "length": "72",
        "checksum": "0x3969",
        "ls_seq_number": "800001FD",
        "advertising_router": "100.3.3.3",
        "link_state_id": "100.3.3.3",
        "ls_type": "Router Links",
        "options": "(No TOS-capability, DC)",
        "ls_age": "15",
        "links": [
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Network Mask",
            "link_data": "255.255.255.255",
            "link_id_label": "Network/subnet number",
            "link_id": "100.3.3.3",
            "link_type": "a Stub Network"
          },
          {
            "tos0_metrics": "1",
            "mtid_metrics": "0",
            "link_data_label": "Router Interface address",
            "link_data": "192.168.4.1",
