=== Madolkke/cli-parser/evals/test_sets/arista_eos.show_version/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "model": {
      "type": "string"
    },
    "hardware_version": {
      "type": "string"
    },
    "serial_number": {
      "type": "string"
    },
    "hardware_mac_address": {
      "type": "string"
    },
    "system_mac_address": {
      "type": "string"
    },
    "software_image_version": {
      "type": "string"
    },
    "architecture": {
      "type": "string"
    },
    "internal_build_version": {
      "type": "string"
    },
    "internal_build_id": {
      "type": "string"
    },
    "image_format_version": {
      "type": "string"
    },
    "image_optimization": {
      "type": "string"
    },
    "uptime": {
      "type": "string"
    },
    "total_memory": {
      "type": "string"
    },
    "free_memory": {
      "type": "string"
    }
  },
  "required": [
    "model",
    "hardware_version",
    "serial_number",
    "hardware_mac_address",
    "system_mac_address",
    "software_image_version",
    "architecture",
    "internal_build_version",
    "internal_build_id",
    "image_format_version",
    "image_optimization",
    "uptime",
    "total_memory",
    "free_memory"
  ]
}

=== Madolkke/cli-parser/evals/test_sets/arista_eos.show_version/expected.json
[
  {
    "free_memory": "1807180 kB",
    "total_memory": "3982820 kB",
    "uptime": "134 weeks, 5 days, 23 hours and 44 minutes",
    "image_optimization": "DEFAULT",
    "image_format_version": "2.0",
    "internal_build_id": "f62c8154-2e05-4650-be1e-c30774deec7e",
    "internal_build_version": "4.27.6M-28481162.4276M",
    "architecture": "i686",
    "software_image_version": "4.27.6M",
    "system_mac_address": "fcbd.67c7.ffe7",
    "hardware_mac_address": "fcbd.67c7.ffe7",
    "serial_number": "JPE11400249",
    "hardware_version": "11.00",
    "model": "CCS-720XP-24ZY4-F"
  },
  {
    "free_memory": "2076700 kB",
    "total_memory": "3982456 kB",
    "uptime": "3 weeks, 0 days, 20 hours and 45 minutes",
    "image_optimization": "Strata-4GB",
    "image_format_version": "3.0",
    "internal_build_id": "ecbeee98-6249-4e05-84e6-60b46a08f83e",
    "internal_build_version": "4.28.9M-33818481.4289M",
    "architecture": "i686",
    "software_image_version": "4.28.9M",
    "system_mac_address": "985d.82b8.faf5",
    "hardware_mac_address": "985d.82b8.faf5",
    "serial_number": "JPE18523609",
    "hardware_version": "12.03",
    "model": "DCS-7010T-48-R"
  }
]
