=== Madolkke/cli-parser/evals/disabled_test_sets/juniper_junos.show_system_uptime/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "current_time": {
      "type": "string"
    },
    "time_source": {
      "type": "string"
    },
    "system_booted": {
      "type": "string"
    },
    "protocols_started": {
      "type": "string"
    },
    "last_configured": {
      "type": "string"
    },
    "cli_time": {
      "type": "string"
    },
    "cli_uptime": {
      "type": "string"
    },
    "users": {
      "type": "string"
    },
    "load_average_1m": {
      "type": "string"
    },
    "load_average_5m": {
      "type": "string"
    },
    "load_average_15m": {
      "type": "string"
    }
  },
  "required": [
    "current_time",
    "time_source",
    "system_booted",
    "protocols_started",
    "last_configured",
    "cli_time",
    "cli_uptime",
    "users",
    "load_average_1m",
    "load_average_5m",
    "load_average_15m"
  ]
}

=== Madolkke/cli-parser/evals/disabled_test_sets/juniper_junos.show_system_uptime/expected.json
[
  {
    "cli_time": "8:48AM",
    "cli_uptime": "154 days, 19:16",
    "users": "2",
    "load_average_1m": "0.04",
    "load_average_5m": "0.04",
    "load_average_15m": "0.01",
    "last_configured": "2021-07-13 16:35:35 MSK (6w6d 16:12 ago) by admin",
    "protocols_started": "2021-03-29 13:37:11 MSK (22w0d 19:11 ago)",
    "system_booted": "2021-03-29 13:32:05 MSK (22w0d 19:16 ago)",
    "time_source": "NTP CLOCK",
    "current_time": "2021-08-31 08:48:11 MSK"
  },
  {
    "cli_time": "12:29PM",
    "cli_uptime": "185 days, 17:59",
    "users": "1",
    "load_average_1m": "0.11",
    "load_average_5m": "0.05",
    "load_average_15m": "0.01",
    "last_configured": "2021-07-13 16:35:18 MSK (6w6d 19:54 ago) by admin",
    "protocols_started": "2021-02-26 18:34:06 MSK (26w3d 17:55 ago)",
    "system_booted": "2021-02-26 18:30:12 MSK (26w3d 17:59 ago)",
    "time_source": "NTP CLOCK",
    "current_time": "2021-08-31 12:29:34 MSK"
  }
]
