=== Madolkke/cli-parser/evals/test_sets/broadcom_icos.show_version/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "switch": {
      "type": "string"
    },
    "system_description": {
      "type": "string"
    },
    "machine_type": {
      "type": "string"
    },
    "machine_model": {
      "type": "string"
    },
    "serial_number": {
      "type": "string"
    },
    "maintenance_level": {
      "type": "string"
    },
    "manufacturer": {
      "type": "string"
    },
    "burned_in_mac_address": {
      "type": "string"
    },
    "software_version": {
      "type": "string"
    },
    "operating_system": {
      "type": "string"
    },
    "network_processing_device": {
      "type": "string"
    },
    "additional_packages": {
      "type": "string"
    },
    "cpld_version": {
      "type": "string"
    },
    "board_revision": {
      "type": "string"
    },
    "fru_number": {
      "type": "string"
    },
    "part_number": {
      "type": "string"
    }
  },
  "required": [
    "switch",
    "system_description",
    "machine_type",
    "machine_model",
    "serial_number",
    "maintenance_level",
    "manufacturer",
    "burned_in_mac_address",
    "software_version",
    "operating_system",
    "network_processing_device",
    "additional_packages"
  ]
}

=== Madolkke/cli-parser/evals/test_sets/broadcom_icos.show_version/expected.json
[
  {
    "network_processing_device": "BCM56340_A0",
    "operating_system": "Linux 3.6.5",
    "software_version": "3.2.2.42",
    "burned_in_mac_address": "A8:2B:B5:55:58:01",
    "manufacturer": "0xbc00",
    "maintenance_level": "A",
    "serial_number": "EC1726004357",
    "machine_model": "BCM-56643",
    "machine_type": "Accton AS4610-54P",
    "system_description": "Accton AS4610-54P , 3.2.2.42, Linux 3.6.5, U-Boot 2012.10-gd563f4a (Apr 13 2017 - 12:08:06) - 2012.10.0.5",
    "switch": "1",
    "additional_packages": "BGP-4 QOS Multicast IPv6 Routing Data Center OpEN API Prototype Open API"
  },
  {
    "board_revision": "0x2",
    "cpld_version": "0x2",
    "network_processing_device": "BCM56846_A1",
    "operating_system": "Linux 3.8.13-rt9-4143e257",
    "software_version": "3.2.2.42",
    "burned_in_mac_address": "A8:2B:B5:57:CC:8D",
    "manufacturer": "0xbc00",
    "maintenance_level": "A",
    "serial_number": "561052X1727264",
    "machine_model": "AS5610-52X",
    "machine_type": "Data Center Switch Software AS5610-52X, 48x10Gb, 4x40Gb",
    "system_description": "Data Center Switch Software AS5610-52X, 48x10Gb, 4x40Gb, 3.2.2.42, Linux 3.8.13-rt9-4143e257, U-Boot 2013.01.01-gb4d916c (Jun 06 2017 - 10:45:46) - 3.0.3.15",
    "switch": "1",
    "additional_packages": "BGP-4 QOS Multicast IPv6 Routing Data Center OpEN API Prototype Open API"
  },
  {
    "cpld_version": "0x1",
    "network_processing_device": "BCM56846_A1",
    "operating_system": "Linux 3.8.13-rt9-4143e257",
    "software_version": "3.2.2.42",
    "burned_in_mac_address": "2C:60:0C:C0:6A:0C",
    "manufacturer": "0xbc00",
    "maintenance_level": "A",
    "fru_number": "1LY2BZZ001A",
    "serial_number": "QTFCEA530009C",
    "machine_model": "LY2R",
    "machine_type": "LY2R - 48 TENGIG, Four 40GbE  PORTS",
    "system_description": "LY2R - 48 TENGIG, Four 40GbE  PORTS, 3.2.2.42, Linux 3.8.13-rt9-4143e257, U-Boot 2010.12 (Feb 10 2015 - 10:01:12) - ONIE 2014.05.03-d",
    "switch": "1",
    "additional_packages": "BGP-4 QOS Multicast IPv6 Routing Data Center OpEN API Prototype Open API"
  },
  {
    "network_processing_device": "BCM56538_B0",
    "operating_system": "Linux 2.6.34.6",
    "software_version": "2.3.2.12",
    "burned_in_mac_address": "08:9E:01:A0:32:FC",
    "manufacturer": "0xbc00",
    "maintenance_level": "A",
    "part_number": "BCM56538",
    "fru_number": "1LB9BZZ0STK",
    "serial_number": "QTFCA63150162",
    "machine_model": "LB9",
    "machine_type": "Quanta LB9",
    "system_description": "Quanta LB9, 2.3.2.12, Linux 2.6.34.6, U-Boot 1.3.0 (Dec 14 2012 - 10:30:09)",
    "switch": "1",
    "additional_packages": "BGP-4 QOS IPv6 Routing Data Center OpEN API Prototype Open API"
  },
  {
    "board_revision": "0x5",
    "cpld_version": "0xd",
    "network_processing_device": "BCM56340_A0",
    "operating_system": "Linux 3.6.5-c428db7a",
    "software_version": "3.2.2.42",
    "burned_in_mac_address": "00:30:AB:F2:48:DE",
    "manufacturer": "0xbc00",
    "maintenance_level": "A",
    "serial_number": "3448BCN1603101",
    "machine_model": "BCM-56340",
    "machine_type": "DNI-3448P 48x1Gb POE, 2x10G, 2x20G Helix4 L3 System",
    "system_description": "DNI-3448P 48x1Gb POE, 2x10G, 2x20G Helix4 L3 System, 3.2.2.42, Linux 3.6.5-c428db7a",
    "switch": "1",
    "additional_packages": "BGP-4 QOS Multicast IPv6 Routing Data Center OpEN API Prototype Open API"
  }
]
