=== Madolkke/cli-parser/evals/test_sets/mikrotik_routeros.system_resource_print/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "uptime": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "build_time": {
      "type": "string"
    },
    "factory_software": {
      "type": "string"
    },
    "free_memory": {
      "type": "string"
    },
    "total_memory": {
      "type": "string"
    },
    "cpu": {
      "type": "string"
    },
    "cpu_count": {
      "type": "string"
    },
    "cpu_frequency": {
      "type": "string"
    },
    "cpu_load": {
      "type": "string"
    },
    "free_hdd_space": {
      "type": "string"
    },
    "total_hdd_space": {
      "type": "string"
    },
    "write_sect_since_reboot": {
      "type": "string"
    },
    "write_sect_total": {
      "type": "string"
    },
    "bad_blocks": {
      "type": "string"
    },
    "architecture_name": {
      "type": "string"
    },
    "board_name": {
      "type": "string"
    },
    "platform": {
      "type": "string"
    }
  },
  "required": [
    "uptime",
    "version",
    "build_time",
    "free_memory",
    "total_memory",
    "cpu",
    "cpu_count",
    "cpu_load",
    "free_hdd_space",
    "total_hdd_space",
    "write_sect_since_reboot",
    "write_sect_total",
    "architecture_name",
    "board_name",
    "platform"
  ]
}

=== Madolkke/cli-parser/evals/test_sets/mikrotik_routeros.system_resource_print/expected.json
[
  {
    "platform": "MikroTik",
    "board_name": "hEX PoE lite",
    "architecture_name": "mipsbe",
    "bad_blocks": "0%",
    "write_sect_total": "572180",
    "write_sect_since_reboot": "44663",
    "total_hdd_space": "16.0MiB",
    "free_hdd_space": "1196.0KiB",
    "cpu_load": "1%",
    "cpu_frequency": "650MHz",
    "cpu_count": "1",
    "cpu": "MIPS 24Kc V7.4",
    "total_memory": "64.0MiB",
    "free_memory": "40.2MiB",
    "build_time": "Dec/03/2021 12:15:05",
    "version": "6.48.6 (long-term)",
    "uptime": "6w5d11h55m45s"
  },
  {
    "platform": "MikroTik",
    "board_name": "hEX PoE lite",
    "architecture_name": "mipsbe",
    "bad_blocks": "0%",
    "write_sect_total": "77652",
    "write_sect_since_reboot": "1970",
    "total_hdd_space": "16.0MiB",
    "free_hdd_space": "3428.0KiB",
    "cpu_load": "1%",
    "cpu_frequency": "650MHz",
    "cpu_count": "1",
    "cpu": "MIPS 24Kc V7.4",
    "total_memory": "64.0MiB",
    "free_memory": "45.5MiB",
    "factory_software": "6.44.6",
    "build_time": "May/23/2023 05:27:08",
    "version": "6.48.7 (long-term)",
    "uptime": "1d6h22m"
  },
  {
    "platform": "MikroTik",
    "board_name": "CHR",
    "architecture_name": "x86_64",
    "write_sect_total": "213432",
    "write_sect_since_reboot": "213432",
    "total_hdd_space": "89.2MiB",
    "free_hdd_space": "69.8MiB",
    "cpu_load": "53%",
    "cpu_frequency": "2294MHz",
    "cpu_count": "2",
    "cpu": "Common",
    "total_memory": "192.0MiB",
    "free_memory": "36.7MiB",
    "factory_software": "7.1",
    "build_time": "Dec/20/2023 08:41:00",
    "version": "7.12.2 (stable)",
    "uptime": "5w3d20m51s"
  },
  {
    "platform": "MikroTik",
    "board_name": "CCR2004-1G-12S+2XS",
    "architecture_name": "arm64",
    "bad_blocks": "0%",
    "write_sect_total": "291965",
    "write_sect_since_reboot": "54120",
    "total_hdd_space": "128.0MiB",
    "free_hdd_space": "104.4MiB",
    "cpu_load": "36%",
    "cpu_count": "4",
    "cpu": "ARM64",
    "total_memory": "4032.0MiB",
    "free_memory": "3704.1MiB",
    "factory_software": "7.6",
    "build_time": "Dec/20/2023 08:41:00",
    "version": "7.12.2 (stable)",
    "uptime": "10w2d6h21m59s"
  }
]
